/*Still under devlopment*/
SELECT ExCl.EXT_CLIENT_ID
	,RECORD_NAME
	,RECORD_STATUS_2_C
	,APPLICATION_IDENTIFIER
	,USER_ACCT_INI
	,ACTIVATED_STATUS_OVERRIDE_C
	,ORIGIN_C
	,ACCESS_TOKEN_EXP_MINUTES
	,EXP_DUE_TO_INACTIVITY_YN
	,REFRESH_TOKEN_EXP_HOURS
	,RECORD_CREATION_DATE
	,APPLICATION_WEBSITE
	,VENDOR_WEBSITE
	,PRIMARY_FHIR_VERSION_C
	,UNIVERSAL_CLIENT_ID
	,GRANT_FUNDED_YN
	,DYN_CLI_EXP_POLCY_C
	,CAN_REG_DYNAMIC_CLIENT_C
	,FHIR_ID_VERSION_C
	,ExClCon.ACTIVATED_STATUS_C
	,ZAS.TITLE
	,ExClCon.*
FROM dbo.EXTERNAL_CLIENTS ExCl
JOIN (select EXT_CLIENT_ID, CONTACT_DATE_REAL = MAX(CONTACT_DATE_REAL) from EXTERNAL_CLIENT_CONTACTS GROUP BY EXT_CLIENT_ID) LatestContact ON ExCl.EXT_CLIENT_ID = LatestContact.EXT_CLIENT_ID
LEFT JOIN EXTERNAL_CLIENT_CONTACTS ExClCon on LatestContact.EXT_CLIENT_ID = ExClCon.EXT_CLIENT_ID and LatestContact.CONTACT_DATE_REAL = ExClCon.CONTACT_DATE_REAL
LEFT JOIN ZC_ACTIVATED_STATUS ZAS on ExClCon.ACTIVATED_STATUS_C = ZAS.ACTIVATED_STATUS_C 
WHERE 1=1
--AND (ExClCon.ACTIVATED_STATUS_C IS NULL Or ExClCon.ACTIVATED_STATUS_C not in (3))
--Where RECORD_NAME like 'zocdoc'
--AND RECORD_NAME like '%Test%'
--AND APPLICATION_NAME like '%salinas%'
AND ExCl.USER_ACCT_INI <> 'WPR'

--select * from EXTERNAL_CLIENT_CONTACTS

