SELECT ser.PROV_ID
	,ser.PROV_NAME
	,ser.SEX
	,ser2.NPI
	,SER.USER_ID
	,emp.SYSTEM_LOGIN
	,MSOWid.IDENTITY_ID AS MSOW_ID
	,PROVid.IDENTITY_ID AS PROVIDER_ID_MPI
	,NPIid.IDENTITY_ID AS NPI_ID
	,ser.ACTIVE_STATUS
	,ser.EMP_STATUS
	,ser.DOCTORS_DEGREE
	,ser.CLINICIAN_TITLE
	,PROVIDER_TYPE = ISNULL(ZC_NOTE_SER.NAME, '')
	,ser.TAKING_NEW_PAT_YN
	,EMPNAME.FIRST_NAME
	,EMPNAME.MIDDLE_NAME
	,EMPNAME.LAST_NAME
	,SPECIALTY
FROM dbo.CLARITY_SER ser
INNER JOIN dbo.CLARITY_SER_2 ser2 ON ser.PROV_ID = ser2.PROV_ID
LEFT OUTER JOIN dbo.IDENTITY_SER_ID MSOWid ON ser.PROV_ID = MSOWid.PROV_ID  AND MSOWid.IDENTITY_TYPE_ID = 137 --MSOW [137]
LEFT OUTER JOIN dbo.IDENTITY_SER_ID PROVid ON ser.PROV_ID = PROVid.PROV_ID  AND PROVid.IDENTITY_TYPE_ID = 6 --PROVIDER ID [6]
LEFT OUTER JOIN dbo.IDENTITY_SER_ID NPIid ON ser.PROV_ID = NPIid.PROV_ID  AND NPIid.IDENTITY_TYPE_ID = 60 --PROVIDER NPI [60]
LEFT OUTER JOIN dbo.CLARITY_EMP emp ON ser.PROV_ID = emp.PROV_ID
LEFT JOIN  (
SELECT PROV_ID,
	SPECIALTY = STRING_AGG(TITLE,' ~ ') WITHIN GROUP (Order by LINE ASC)
FROM CLARITY.DBO.CLARITY_SER_SPEC Spec WITH (NOLOCK)
LEFT JOIN CLARITY.DBO.ZC_SPECIALTY WITH (NOLOCK) ON Spec.[SPECIALTY_C] = [ZC_SPECIALTY].[SPECIALTY_C]
GROUP BY PROV_ID) Spec on SER.PROV_ID = Spec.PROV_ID
LEFT OUTER JOIN CLARITY.DBO.ZC_NOTE_SER WITH (NOLOCK) ON SER.PROVIDER_TYPE_C = [ZC_NOTE_SER].[SERVICE_TYPE_C]
OUTER APPLY (
SELECT TOP 1
	--USER_ID
	--,CL_EMP_OT_CSN_ID
	--,USER_NAME_EXT_OT
	--,CONTACT_COMMENT
	EMP_NAME_RECORD_ID
	,FIRST_NAME
	,MIDDLE_NAME
	,LAST_NAME	
	,RECORD_CREATION_DT
	,INSTANT_OF_UPD_TM
FROM CLARITY.dbo.CL_EMP_OT EMP_OT
LEFT JOIN CLARITY.dbo.NAMES_STATIC FML_Names on EMP_OT.EMP_NAME_RECORD_ID = FML_Names.RECORD_ID --Non-Patient Person Name (EAM) 
WHERE EMP_OT.USER_ID = SER.USER_ID
AND FML_Names.FIRST_NAME is not null -- get the latest available name on file.
AND FML_Names.RECORD_STATUS_C is null -- do not show deleted records
ORDER BY CL_EMP_OT_CSN_ID DESC
) AS EMPNAME
WHERE 1=1
AND SER.USER_ID is not null
